from datetime import datetime
from typing import Final

from pydantic import BaseModel, ConfigDict, Field, field_validator

from solgreen.contracts.enums import SignalKind
from solgreen.contracts.validity import ValidityFlags

SignalValue = float | str | None


class SignalSpec(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    index: int = Field(ge=1, le=120)
    canonical_name: str
    original_es: str
    original_en: str | None
    kind: SignalKind
    unit: str
    group: str
    priority: bool = Field(description="True si es señal prioritaria del MVP.")


SIGNAL_SPECS: Final[tuple[SignalSpec, ...]] = (
    SignalSpec(
        index=1,
        canonical_name="nombre_del_dispositivo",
        original_es="Nombre del dispositivo",
        original_en=None,
        kind=SignalKind.TEXT,
        unit="text",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=2,
        canonical_name="numero_de_serie",
        original_es="número de serie",
        original_en=None,
        kind=SignalKind.TEXT,
        unit="text",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=3,
        canonical_name="dispositivo_principal",
        original_es="Dispositivo principal",
        original_en=None,
        kind=SignalKind.TEXT,
        unit="text",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=4,
        canonical_name="numero_de_serie_del_dispositivo",
        original_es="Número de serie del dispositivo",
        original_en=None,
        kind=SignalKind.TEXT,
        unit="text",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=5,
        canonical_name="hora_actualizada",
        original_es="Hora actualizada",
        original_en=None,
        kind=SignalKind.TIME,
        unit="time",
        group="identificacion",
        priority=True,
    ),
    SignalSpec(
        index=6,
        canonical_name="nombre_del_dispositivo_b",
        original_es="Nombre del dispositivo",
        original_en=None,
        kind=SignalKind.TEXT,
        unit="text",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=7,
        canonical_name="pv_open_circuit_voltage_v",
        original_es="PV Open Circuit Voltage(V)",
        original_en="PV Open Circuit Voltage",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="pv_mppt",
        priority=False,
    ),
    SignalSpec(
        index=8,
        canonical_name="pv_maximum_charging_current_a",
        original_es="PV Maximum Charging Current(A)",
        original_en="PV Maximum Charging Current",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="pv_mppt",
        priority=False,
    ),
    SignalSpec(
        index=9,
        canonical_name="rated_output_power_w",
        original_es="Rated Output Power(W)",
        original_en="Rated Output Power",
        kind=SignalKind.POWER_W,
        unit="W",
        group="pv_mppt",
        priority=False,
    ),
    SignalSpec(
        index=10,
        canonical_name="parallel_mode",
        original_es="Parallel Mode",
        original_en=None,
        kind=SignalKind.TEXT,
        unit="text",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=11,
        canonical_name="hora_del_sistema",
        original_es="Hora del sistema",
        original_en=None,
        kind=SignalKind.TIME,
        unit="time",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=12,
        canonical_name="current_state_of_machine",
        original_es="Current state of machine",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="estados",
        priority=True,
    ),
    SignalSpec(
        index=13,
        canonical_name="bms_version1",
        original_es="BMS Version1",
        original_en=None,
        kind=SignalKind.VERSION,
        unit="version",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=14,
        canonical_name="bms_version2",
        original_es="BMS Version2",
        original_en=None,
        kind=SignalKind.VERSION,
        unit="version",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=15,
        canonical_name="software_version_number_1",
        original_es="Software Version Number 1",
        original_en=None,
        kind=SignalKind.VERSION,
        unit="version",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=16,
        canonical_name="software_version_number_2",
        original_es="Software Version Number 2",
        original_en=None,
        kind=SignalKind.VERSION,
        unit="version",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=17,
        canonical_name="hardware_version",
        original_es="Hardware Version",
        original_en=None,
        kind=SignalKind.VERSION,
        unit="version",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=18,
        canonical_name="software_version_number_4",
        original_es="Software Version Number 4",
        original_en=None,
        kind=SignalKind.VERSION,
        unit="version",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=19,
        canonical_name="upgrade_flag_bit",
        original_es="Upgrade Flag Bit",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=20,
        canonical_name="minor_version_number",
        original_es="Minor version number",
        original_en=None,
        kind=SignalKind.VERSION,
        unit="version",
        group="identificacion",
        priority=False,
    ),
    SignalSpec(
        index=21,
        canonical_name="voltaje_cc_pv1_v",
        original_es="Voltaje CC PV1(V)",
        original_en="PV1 Voltage",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="pv_mppt",
        priority=True,
    ),
    SignalSpec(
        index=22,
        canonical_name="voltaje_cc_pv2_v",
        original_es="Voltaje CC PV2(V)",
        original_en="PV2 Voltage",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="pv_mppt",
        priority=True,
    ),
    SignalSpec(
        index=23,
        canonical_name="corriente_cc_pv1_a",
        original_es="Corriente CC PV1(A)",
        original_en="PV1 Current",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="pv_mppt",
        priority=True,
    ),
    SignalSpec(
        index=24,
        canonical_name="corriente_cc_pv2_a",
        original_es="Corriente CC PV2(A)",
        original_en="PV2 Current",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="pv_mppt",
        priority=True,
    ),
    SignalSpec(
        index=25,
        canonical_name="potencia_cc_pv1_w",
        original_es="Potencia CC PV1(W)",
        original_en="PV1 Power",
        kind=SignalKind.POWER_W,
        unit="W",
        group="pv_mppt",
        priority=True,
    ),
    SignalSpec(
        index=26,
        canonical_name="potencia_cc_pv2_w",
        original_es="Potencia CC PV2(W)",
        original_en="PV2 Power",
        kind=SignalKind.POWER_W,
        unit="W",
        group="pv_mppt",
        priority=True,
    ),
    SignalSpec(
        index=27,
        canonical_name="voltaje_ca_r_u_a_v",
        original_es="Voltaje CA R/U/A(V)",
        original_en="AC Voltage R/U/A",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=28,
        canonical_name="voltaje_ca_s_v_b_v",
        original_es="Voltaje CA S/V/B(V)",
        original_en="AC Voltage S/V/B",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=29,
        canonical_name="corriente_ca_r_u_a_a",
        original_es="Corriente CA R/U/A(A)",
        original_en="AC Current R/U/A",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=30,
        canonical_name="corriente_ca_s_v_b_a",
        original_es="Corriente CA S/V/B(A)",
        original_en="AC Current S/V/B",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=31,
        canonical_name="frecuencia_r_de_salida_de_ca_hz",
        original_es="Frecuencia R de salida de CA(Hz)",
        original_en="AC Output Frequency R",
        kind=SignalKind.FREQUENCY_HZ,
        unit="Hz",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=32,
        canonical_name="frecuencia_de_salida_ca_s_hz",
        original_es="Frecuencia de salida CA S(Hz)",
        original_en="AC Output Frequency S",
        kind=SignalKind.FREQUENCY_HZ,
        unit="Hz",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=33,
        canonical_name="potencia_total_ca_w",
        original_es="Potencia total CA (activa)(W)",
        original_en="Total AC Power (active)",
        kind=SignalKind.POWER_W,
        unit="W",
        group="salida_ac",
        priority=True,
    ),
    SignalSpec(
        index=34,
        canonical_name="produccion_acumulada_kwh",
        original_es="Producción acumulada (activa)(kWh)",
        original_en="Cumulative production (active)",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=35,
        canonical_name="produccion_diaria_kwh",
        original_es="Producción diaria (activa)(kWh)",
        original_en="Daily production (active)",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="salida_ac",
        priority=False,
    ),
    SignalSpec(
        index=36,
        canonical_name="pv_total_charging_power_w",
        original_es="PV Total Charging Power(W)",
        original_en="PV Total Charging Power",
        kind=SignalKind.POWER_W,
        unit="W",
        group="pv_mppt",
        priority=False,
    ),
    SignalSpec(
        index=37,
        canonical_name="total_charging_power_w",
        original_es="Total Charging Power (PV + Mains)(W)",
        original_en="Total Charging Power (PV + Mains)",
        kind=SignalKind.POWER_W,
        unit="W",
        group="pv_mppt",
        priority=False,
    ),
    SignalSpec(
        index=38,
        canonical_name="daily_generator_output_kwh",
        original_es="Daily generator output(kWh)",
        original_en="Daily generator output",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=39,
        canonical_name="total_generator_output_kwh",
        original_es="Total generator output(kWh)",
        original_en="Total generator output",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=40,
        canonical_name="estado_de_red",
        original_es="Estado de red",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=41,
        canonical_name="frecuencia_de_red_hz",
        original_es="Frecuencia de red(Hz)",
        original_en="Grid frequency",
        kind=SignalKind.FREQUENCY_HZ,
        unit="Hz",
        group="red",
        priority=True,
    ),
    SignalSpec(
        index=42,
        canonical_name="alimentacion_acumulada_de_red_kwh",
        original_es="Alimentación acumulada de red(kWh)",
        original_en="Cumulative grid feed-in",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=43,
        canonical_name="energia_adquirida_acumulada_kwh",
        original_es="Energía adquirida acumulada(kWh)",
        original_en="Cumulative grid import",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=44,
        canonical_name="alimentacion_diaria_de_red_kwh",
        original_es="Alimentación diaria de red(kWh)",
        original_en="Daily grid feed-in",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=45,
        canonical_name="energia_diaria_adquirida_kwh",
        original_es="Energía diaria adquirida(kWh)",
        original_en="Daily grid import",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=46,
        canonical_name="battery_charging_of_the_day_by_utility_grid_ah",
        original_es="Battery Charging Of The Day By Utility Grid (Ah)(AH)",
        original_en="Battery Charging Of The Day By Utility Grid",
        kind=SignalKind.ENERGY_WH,
        unit="AH",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=47,
        canonical_name="share_the_amount_of_charge_on_the_same_day_kwh",
        original_es="Share the amount of charge on the same day(kWh)",
        original_en="Share the amount of charge on the same day",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=48,
        canonical_name="cumulative_charge_of_utility_power_kwh",
        original_es="Cumulative Charge Of Utility Power(kWh)",
        original_en="Cumulative Charge Of Utility Power",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=49,
        canonical_name="mains_charging_power_w",
        original_es="Mains Charging Power(W)",
        original_en="Mains Charging Power",
        kind=SignalKind.POWER_W,
        unit="W",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=50,
        canonical_name="total_active_power_of_the_grid_w",
        original_es="Total Active Power Of The Grid(W)",
        original_en="Total Active Power Of The Grid",
        kind=SignalKind.POWER_W,
        unit="W",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=51,
        canonical_name="utility_charge_current_a",
        original_es="Utility Charge Current(A)",
        original_en="Utility Charge Current",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=52,
        canonical_name="l1_utility_active_power_w",
        original_es="L1 Utility Active Power(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="red",
        priority=True,
    ),
    SignalSpec(
        index=53,
        canonical_name="l2_utility_active_power_w",
        original_es="L2 Utility Active Power(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="red",
        priority=True,
    ),
    SignalSpec(
        index=54,
        canonical_name="l1_utility_apparent_power_va",
        original_es="L1 Utility Apparent power(VA)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="VA",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=55,
        canonical_name="l2_utility_apparent_power_va",
        original_es="L2 Utility Apparent power(VA)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="VA",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=56,
        canonical_name="total_charging_amount_of_mains_ah",
        original_es="Total charging amount of mains(AH)",
        original_en=None,
        kind=SignalKind.ENERGY_WH,
        unit="AH",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=57,
        canonical_name="grid_code",
        original_es="Grid Code",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="red",
        priority=True,
    ),
    SignalSpec(
        index=58,
        canonical_name="l1_mains_voltage_v",
        original_es="L1 Mains Voltage(V)",
        original_en=None,
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="red",
        priority=True,
    ),
    SignalSpec(
        index=59,
        canonical_name="l1_mains_current_a",
        original_es="L1 Mains Current(A)",
        original_en=None,
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=60,
        canonical_name="l2_mains_voltage_v",
        original_es="L2 Mains Voltage(V)",
        original_en=None,
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="red",
        priority=True,
    ),
    SignalSpec(
        index=61,
        canonical_name="l2_mains_current_a",
        original_es="L2 Mains Current(A)",
        original_en=None,
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="red",
        priority=False,
    ),
    SignalSpec(
        index=62,
        canonical_name="potencia_de_carga_l1_w",
        original_es="Potencia de carga L1(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="cargas",
        priority=True,
    ),
    SignalSpec(
        index=63,
        canonical_name="potencia_de_carga_l2_w",
        original_es="Potencia de carga L2(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="cargas",
        priority=True,
    ),
    SignalSpec(
        index=64,
        canonical_name="corriente_de_salida_r_u_a_a",
        original_es="Corriente de salida R/U/A(A)",
        original_en="Output current R/U/A",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=65,
        canonical_name="corriente_consumida_s_v_b_a",
        original_es="Corriente consumida S/V/B(A)",
        original_en="Consumed current S/V/B",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=66,
        canonical_name="potencia_de_consumo_total_w",
        original_es="Potencia de consumo total(W)",
        original_en="Total load active power",
        kind=SignalKind.POWER_W,
        unit="W",
        group="cargas",
        priority=True,
    ),
    SignalSpec(
        index=67,
        canonical_name="potencia_aparente_de_consumo_total_va",
        original_es="Potencia aparente de consumo total(VA)",
        original_en="Total load apparent power",
        kind=SignalKind.POWER_W,
        unit="VA",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=68,
        canonical_name="consumo_total_kwh",
        original_es="Consumo total(kWh)",
        original_en="Cumulative consumption",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=69,
        canonical_name="consumo_diario_kwh",
        original_es="Consumo diario(kWh)",
        original_en="Daily consumption",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=70,
        canonical_name="l1_load_rate_pct",
        original_es="L1 Load Rate(%)",
        original_en=None,
        kind=SignalKind.RATIO_PCT,
        unit="%",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=71,
        canonical_name="l2_load_rate_pct",
        original_es="L2 Load Rate(%)",
        original_en=None,
        kind=SignalKind.RATIO_PCT,
        unit="%",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=72,
        canonical_name="load_rate_of_whole_machine_pct",
        original_es="Load Rate Of Whole Machine(%)",
        original_en=None,
        kind=SignalKind.RATIO_PCT,
        unit="%",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=73,
        canonical_name="l1_load_apparent_power_va",
        original_es="L1 Load Apparent Power(VA)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="VA",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=74,
        canonical_name="l2_load_apparent_power_va",
        original_es="L2 Load Apparent Power(VA)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="VA",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=75,
        canonical_name="household_load_side_power_l1_w",
        original_es="Household Load Side Power L1(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=76,
        canonical_name="household_load_side_power_l2_w",
        original_es="Household Load Side Power L2(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="cargas",
        priority=False,
    ),
    SignalSpec(
        index=77,
        canonical_name="bus_voltage_v",
        original_es="BUS voltage(V)",
        original_en="BUS voltage",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="bus",
        priority=True,
    ),
    SignalSpec(
        index=78,
        canonical_name="positive_bus_voltage_v",
        original_es="Positive BUS voltage(V)",
        original_en=None,
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="bus",
        priority=False,
    ),
    SignalSpec(
        index=79,
        canonical_name="negative_bus_voltage_v",
        original_es="Negative BUS voltage(V)",
        original_en=None,
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="bus",
        priority=False,
    ),
    SignalSpec(
        index=80,
        canonical_name="output_frequency_hz",
        original_es="Output frequency(Hz)",
        original_en="Output frequency",
        kind=SignalKind.FREQUENCY_HZ,
        unit="Hz",
        group="bus",
        priority=True,
    ),
    SignalSpec(
        index=81,
        canonical_name="estado_de_bateria",
        original_es="Estado de batería",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=82,
        canonical_name="battery_charging_type",
        original_es="Battery Charging Type",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=83,
        canonical_name="voltaje_de_bateria_v",
        original_es="Voltaje de batería(V)",
        original_en="Battery voltage",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="bateria",
        priority=True,
    ),
    SignalSpec(
        index=84,
        canonical_name="corriente_de_bateria_a",
        original_es="Corriente de batería(A)",
        original_en="Battery current",
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="bateria",
        priority=True,
    ),
    SignalSpec(
        index=85,
        canonical_name="potencia_de_bateria_w",
        original_es="Potencia de batería(W)",
        original_en="Battery power",
        kind=SignalKind.POWER_W,
        unit="W",
        group="bateria",
        priority=True,
    ),
    SignalSpec(
        index=86,
        canonical_name="soc_pct",
        original_es="SoC(%)",
        original_en=None,
        kind=SignalKind.SOC_PCT,
        unit="%",
        group="bateria",
        priority=True,
    ),
    SignalSpec(
        index=87,
        canonical_name="energia_de_carga_total_kwh",
        original_es="Energía de carga total(kWh)",
        original_en="Cumulative battery charge",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=88,
        canonical_name="energia_de_descarga_total_kwh",
        original_es="Energía de descarga total(kWh)",
        original_en="Cumulative battery discharge",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=89,
        canonical_name="energia_de_carga_diaria_kwh",
        original_es="Energía de carga diaria(kWh)",
        original_en="Daily battery charge",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=90,
        canonical_name="energia_de_descarga_diaria_kwh",
        original_es="Energía de descarga diaria(kWh)",
        original_en="Daily battery discharge",
        kind=SignalKind.ENERGY_WH,
        unit="kWh",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=91,
        canonical_name="battery_charging_of_the_day_ah",
        original_es="Battery Charging Of The Day (Ah)(AH)",
        original_en=None,
        kind=SignalKind.ENERGY_WH,
        unit="AH",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=92,
        canonical_name="battery_discharging_of_the_day_ah",
        original_es="Battery Discharging Of The Day (Ah)(AH)",
        original_en=None,
        kind=SignalKind.ENERGY_WH,
        unit="AH",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=93,
        canonical_name="cumulative_data_of_battery_charging_ah",
        original_es="Cumulative Data Of Battery Charging (Ah)(AH)",
        original_en=None,
        kind=SignalKind.ENERGY_WH,
        unit="AH",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=94,
        canonical_name="cumulative_data_of_battery_discharging_ah",
        original_es="Cumulative Data Of Battery Discharging (Ah)(AH)",
        original_en=None,
        kind=SignalKind.ENERGY_WH,
        unit="AH",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=95,
        canonical_name="battery_1_status",
        original_es="Battery 1 Status",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="bateria",
        priority=False,
    ),
    SignalSpec(
        index=96,
        canonical_name="temperatura_ambiente_c",
        original_es="Temperatura ambiente(℃)",
        original_en="Ambient temperature",
        kind=SignalKind.TEMPERATURE_C,
        unit="C",
        group="temperaturas",
        priority=True,
    ),
    SignalSpec(
        index=97,
        canonical_name="inverter_radiator_temperature_c",
        original_es="Inverter radiator temperature(℃)",
        original_en=None,
        kind=SignalKind.TEMPERATURE_C,
        unit="C",
        group="temperaturas",
        priority=True,
    ),
    SignalSpec(
        index=98,
        canonical_name="temperatura_del_transformador_c",
        original_es="Temperatura del transformador(℃)",
        original_en=None,
        kind=SignalKind.TEMPERATURE_C,
        unit="C",
        group="temperaturas",
        priority=False,
    ),
    SignalSpec(
        index=99,
        canonical_name="pv_radiator_temperature_c",
        original_es="PV radiator temperature(℃)",
        original_en=None,
        kind=SignalKind.TEMPERATURE_C,
        unit="C",
        group="temperaturas",
        priority=False,
    ),
    SignalSpec(
        index=100,
        canonical_name="estado_de_inversor",
        original_es="Estado de inversor",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="estados",
        priority=False,
    ),
    SignalSpec(
        index=101,
        canonical_name="system_status",
        original_es="System Status",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="estados",
        priority=True,
    ),
    SignalSpec(
        index=102,
        canonical_name="generator_operation_mode",
        original_es="Generator Operation Mode",
        original_en=None,
        kind=SignalKind.STATUS,
        unit="status",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=103,
        canonical_name="voltaje_de_generador_l1_v",
        original_es="Voltaje de generador L1(V)",
        original_en="Generator voltage L1",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=104,
        canonical_name="voltaje_de_generador_l2_v",
        original_es="Voltaje de generador L2(V)",
        original_en="Generator voltage L2",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=105,
        canonical_name="voltaje_de_generador_l3_v",
        original_es="Voltaje de generador L3(V)",
        original_en="Generator voltage L3",
        kind=SignalKind.VOLTAGE_V,
        unit="V",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=106,
        canonical_name="gen_current_l1_a",
        original_es="Gen Current L1(A)",
        original_en=None,
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=107,
        canonical_name="gen_current_l2_a",
        original_es="Gen Current L2(A)",
        original_en=None,
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=108,
        canonical_name="gen_current_l3_a",
        original_es="Gen Current L3(A)",
        original_en=None,
        kind=SignalKind.CURRENT_A,
        unit="A",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=109,
        canonical_name="generator_active_power_l1_w",
        original_es="Generator Active Power L1(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=110,
        canonical_name="generator_active_power_l2_w",
        original_es="Generator Active Power L2(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=111,
        canonical_name="generator_active_power_l3_w",
        original_es="Generator Active Power L3(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=112,
        canonical_name="generator_apparent_power_l1_va",
        original_es="Generator  Apparent Power L1(VA)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="VA",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=113,
        canonical_name="generator_apparent_power_l2_va",
        original_es="Generator  Apparent Power L2(VA)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="VA",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=114,
        canonical_name="generator_apparent_power_l3_va",
        original_es="Generator  Apparent Power L3(VA)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="VA",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=115,
        canonical_name="frecuencia_generador_hz",
        original_es="Frecuencia generador(Hz)",
        original_en="Generator frequency",
        kind=SignalKind.FREQUENCY_HZ,
        unit="Hz",
        group="generador",
        priority=False,
    ),
    SignalSpec(
        index=116,
        canonical_name="number_of_parallel_machines",
        original_es="Number Of Parallel Machines",
        original_en=None,
        kind=SignalKind.COUNT,
        unit="count",
        group="paralelo",
        priority=False,
    ),
    SignalSpec(
        index=117,
        canonical_name="total_local_load_power_of_parallel_system_w",
        original_es="Total Local Load Power Of Parallel System(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="paralelo",
        priority=False,
    ),
    SignalSpec(
        index=118,
        canonical_name="total_household_load_power_of_parallel_system_w",
        original_es="Total Household Load Power Of Parallel System(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="paralelo",
        priority=False,
    ),
    SignalSpec(
        index=119,
        canonical_name="total_grid_power_of_parallel_system_w",
        original_es="Total Grid Power Of Parallel System(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="paralelo",
        priority=False,
    ),
    SignalSpec(
        index=120,
        canonical_name="total_oil_engine_port_power_of_parallel_system_w",
        original_es="Total Oil Engine Port Power Of Parallel System(W)",
        original_en=None,
        kind=SignalKind.POWER_W,
        unit="W",
        group="paralelo",
        priority=False,
    ),
)

assert len(SIGNAL_SPECS) == 120, f"Se esperaban 120 señales, hay {len(SIGNAL_SPECS)}"

CANONICAL_NAME_TO_INDEX: Final[dict[str, int]] = {s.canonical_name: s.index for s in SIGNAL_SPECS}
ORIGINAL_ES_TO_CANONICAL: Final[dict[str, str]] = {
    s.original_es: s.canonical_name for s in SIGNAL_SPECS
}


class InverterTelemetrySample(BaseModel):
    model_config = ConfigDict(extra="forbid")

    timestamp_original: datetime
    timestamp_utc: datetime
    timezone_source: str | None = None

    device_name: str | None = None
    serial_redacted: str | None = Field(
        default=None,
        description="Serial ofuscado o redaccionado. El original nunca se persiste.",
    )

    signals: dict[str, SignalValue] = Field(default_factory=dict)
    validity: ValidityFlags = Field(default_factory=ValidityFlags)

    @field_validator("signals")
    @classmethod
    def _validate_signal_names(cls, v: dict[str, SignalValue]) -> dict[str, SignalValue]:
        unknown = set(v) - set(CANONICAL_NAME_TO_INDEX)
        if unknown:
            raise ValueError(f"unknown canonical signal names: {sorted(unknown)}")
        return v

    def get_float(self, canonical_name: str) -> float | None:
        value = self.signals.get(canonical_name)
        if isinstance(value, float):
            return value
        if isinstance(value, int) and not isinstance(value, bool):
            return float(value)
        return None

    def get_text(self, canonical_name: str) -> str | None:
        value = self.signals.get(canonical_name)
        if not isinstance(value, str):
            return None
        stripped = value.strip()
        return stripped or None
